// pages/Home.js

import Home from '@/app/Home/page';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const getServerSideProps = async ({ req }) => {
  const userAgent = req.headers['user-agent'] || ''; // Retrieve user-agent from request headers
  return { props: { userAgent } };
};

export default function HomePage({ userAgent }) {
  return <Home userAgent={userAgent} />;
}
